#192 Added hook podAnnotations
newrelic/k8s-metadata-injection pull request #261
Opened 2023-02-24 08:46 UTC by janario

As described at https://github.com/newrelic/k8s-metadata-injection/issues/192

When using istio side car injection the hooks get stuck since the istio container never stops. This PR will provide a way of setting the annotations in the hook to avoid such side car.

2023-02-27 18:26 UTC, nserrino reviewed
Thanks for the contribution, this looks really useful! We will test it on our side and then give you a review shortly.

2023-02-27 23:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/k8s-metadata-injection?pullRequest=261) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/k8s-metadata-injection?pullRequest=261) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/k8s-metadata-injection?pullRequest=261) it.</sub>

2023-03-16 07:31 UTC, htroisi requested changes
Hi @janario thanks for the contribution! 

Could you modify the added field to include a check to see if podAnnotations exist? Like this: 
https://github.com/newrelic/k8s-metadata-injection/blob/main/charts/nri-metadata-injection/templates/deployment.yaml#L17

2023-03-17 20:53 UTC, vihangm approved these changes

2023-03-17 20:55 UTC, htroisi approved these changes

2023-03-17 20:55 UTC, merged